# Generated by Django 5.2.6 on 2026-05-02 09:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('excerpt', models.CharField(blank=True, default='', max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('ประกาศ', 'ประกาศ'), ('กิจกรรม', 'กิจกรรม'), ('ข่าวสาร', 'ข่าวสาร'), ('โอกาสงาน', 'โอกาสงาน')], max_length=20)),
                ('author', models.CharField(blank=True, default='', max_length=100)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='posts/')),
                ('pinned', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pinned', '-created_at'],
            },
        ),
    ]
