# Generated by Django 5.2.6 on 2026-05-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('ประกาศ', 'ประกาศ'), ('กิจกรรม', 'กิจกรรม'), ('ข่าวสาร', 'ข่าวสาร'), ('ประกาศสมัครงาน', 'ประกาศสมัครงาน')], max_length=20),
        ),
    ]
