# Generated by Django 5.2.6 on 2026-05-03 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_category_alter_post_excerpt_alter_post_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='category_ref',
            new_name='category',
        ),
    ]
