# Generated by Django 5.2.6 on 2026-05-26 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_userprofile_github_link_userprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercareer',
            name='end_year',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
