# Generated by Django 5.2.6 on 2026-05-27 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_usercareer_end_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='usereducation',
            name='other_department',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='usereducation',
            name='other_faculty',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
